color: null
fieldLayouts:
  0cd97e1a-97af-452c-a1e3-da97008efece:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 160dd143-fe62-4aff-bd9d-83abe939727b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b13b8ed-b285-47be-8d4f-5eb877a15b47 # Rich Text
            handle: homepageContent
            includeInCards: false
            instructions: 'Rich test content that will appear on the homepage.'
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4b8e952-25a6-4cd3-96ed-c1a6397863d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2054dae6-249e-4d8f-89a0-3d7cd6328057
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
