color: null
fieldLayouts:
  1de651b1-8cc6-4ee9-8cdd-ec741f43221b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1a45ef32-79e2-42d9-ba21-1f8ef6a4e825
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08e25df9-2a4a-4cf5-8c12-c15d3e9dc57e # Plain Text
            handle: newsExcerpt
            includeInCards: false
            instructions: null
            label: 'News Excerpt'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8999c3c1-ff82-4808-947d-0895e96be7ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b13b8ed-b285-47be-8d4f-5eb877a15b47 # Rich Text
            handle: newsBody
            includeInCards: false
            instructions: null
            label: 'News Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3c15b15-0633-48c0-9688-8c037f632772
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 805cc881-8d4f-4c40-9187-cac40a07d9e9
        userCondition: null
handle: marketNews
hasTitleField: true
icon: newspaper
name: 'Market News'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
