dateModified: 1720558199
email:
  fromEmail: ryan@craftquest.io
  fromName: 'House Quest'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/local'
    type: craft\fs\Local
    url: '@web/local'
meta:
  __names__:
    4b13b8ed-b285-47be-8d4f-5eb877a15b47: 'Rich Text' # Rich Text
    06b23d6b-4f3e-4f47-b143-a63e8c522ff6: 'Market News' # Market News
    08e25df9-2a4a-4cf5-8c12-c15d3e9dc57e: 'Plain Text' # Plain Text
    9bebaaa3-6d87-4c75-afc8-f5f75ab950c4: Images # Images
    206b194f-baed-4823-bebf-fd9dd79afe55: Homepage # Homepage
    620caa93-2603-4217-9713-700e82292681: 'Public Schema' # Public Schema
    32097e33-e4c8-46c8-bcb0-c2b35a3cdb32: Homepage # Homepage
    4052097c-4aec-4442-af4c-df0a26b20065: 'Craft 5' # Craft 5
    44100513-40ff-4a13-8799-3b367e512d16: Simple # Simple
    aeab50fd-1aef-41f6-9cb2-1e7e77acf2ff: 'Market News' # Market News
    d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: 'Craft 5' # Craft 5
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: pro
  live: true
  name: 'Craft 5'
  retryDuration: null
  schemaVersion: 5.0.0.21
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
