defaultPlacement: end
enableVersioning: true
entryTypes:
  - 06b23d6b-4f3e-4f47-b143-a63e8c522ff6 # Market News
handle: marketNews
maxAuthors: 1
name: 'Market News'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: true
    template: market-news/_entry
    uriFormat: 'market-news/{slug}'
type: channel
